server:
  port: 3000

pig:
  auth:
    clientId: pig
    clientSecret: pig
    scope: server

spring:
  redis:
    host: 123.206.94.20
    port: 6379
    password: redis
    
logging:
  config: classpath:logback.xml

